### ISSUE TITLE
Replace factory with container

### ISSUE THREAD

**Issue by xepozz** [yiisoft/validator-rule-handler-container#2]
There is no need to create handler every time with factory, especially to have "config" in handler resolver constructor.

No one couldn't answer me about purpose of this change, so I suggest remove it.

See https://github.com/yiisoft/validator-rule-handler-container/pull/1#discussion_r883011718

**Comment by vjik** [comment]
Using factory instead of directly using of `$container->get()` allow separate rule handlers from container. That is, don't configure rule handlers globaly for container of application, instead, configure and use rule handlers with rule handlers container only.

Is it necessary, I don't sure.

**Comment by samdark** [comment]
Separation is a good thing but creating a new instance of handler each time isn't really needed since these are stateless. I'd do it.

**Comment by vjik** [comment]
> Separation is a good thing but creating a new instance of handler each time isn't really needed since these are stateless. I'd do it.

Now instance of rule handler create once, see https://github.com/yiisoft/validator-rule-handler-container/blob/master/src/RuleHandlerContainer.php#L27

**Comment by xepozz** [comment]
It creates once without factory as well. A separation is unnecessary think. Otherwise we should use factory for almost all packages,, but WHY? There is no benefits.

**Comment by samdark** [comment]
@vjik yes, but that's external check. Container would work well without it.
